### ISSUE TITLE
repeat does not follow the specs

### ISSUE THREAD

**Issue by xgbuils** [benji6/imlazy#16]
Hi,

I look that `repeat` method does not follow the specs. It has the correct signature: `repeat a -> [a]` but description and examples is not consistent with the signature:

> Returns a new iterable where every value is the given value and there are as many values as the given count

``` javascript
const repeat42 = repeat(42)
repeat42(3)) // => (42 42 42)
repeat42(Infinity)) // => (42 42 42 42 42 42 42 42 42 42...)
```

Cheers!

**Comment by benji6** [comment]
Oh yeah, looks like I messed up the docs :sweat_smile: I guess I originally implemented it as a binary function, but then I realised there was no need to specify a length as you can take as many as you like from it - that's how it works in Haskell. Thanks for spotting this, should be fixed by #17
