### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by benji6** [benji6/imlazy#20]
It's awesome that in node 8 performance is exceeding that of the native array methods, but can we do better? In particular it would be amazing to gain some sort of parity with transducers. It seems that the extra work being done by imlazy consists in creating intermediate iterables rather than composing transformations directly over a single iterable. This makes imlazy much nicer to use in many ways - intermediate iterables can massively help with code readability and understandability. Transducers are not so easy to understand or use. But maybe there is a way to reduce this extra work while still keeping the iterable interface at each transformation step?

**Comment by benji6** [comment]
I'm going to close this as the benchmark performance has been significantly improved

**Comment by xgbuils** [comment]
> It seems that the extra work being done by imlazy consists in creating intermediate iterables rather than composing transformations directly over a single iterable.

I would like to bring some proves of this:

- https://jsperf.com/create-array-generator-vs-function-generator

- https://jsperf.com/map-composition-vs-map-of-callback-composition

Cheers!
