### ISSUE TITLE
`partition` is caching values.

### ISSUE THREAD

**Issue by xgbuils** [benji6/imlazy#29]
Hi @benji6 

I was reading `partition` implementation and it is implemented breaking your idea about not caching values.

I propose use `filter` for the implementation:

``` javascript
module.exports.partition = curry((f, xs) => genToIter(function * () {
    yield filter(f, xs)
    yield filter(x => !f(x), xs)
}))
```

Cheers!

**Comment by benji6** [comment]
Very true! I think I was being very lazy when I wrote that code! Will push a fix :)
