### ISSUE TITLE
Implement traversable

### ISSUE THREAD

**Issue by masaeedu** [benji6/imlazy#34]
Hi there. Many thanks for the useful library. I see that the library implements `transpose`, but this can be generalized to an implementation of `Traversable` (your pick of `traverse` or [`sequence`](https://github.com/masaeedu/fp/blob/master/src/instances/iter/index.js#L85)), which will let you transpose `(Applicative f) => Iterable (f a)`s into `f (Iterable a)`s.

The degenerate case of `transpose` is then just `sequence`-ing an `Iterable (Iterable a)`.

**Comment by masaeedu** [comment]
I wrote a test to confirm `transpose = sequence(ZipIterable)` works: https://github.com/masaeedu/fp/commit/c10e65fd6fda4cceb82090a20e7aee30849fad7f#diff-5cf74d62b866815bd3844805be3866e7R109, I think the same principle should work for this library.

**Comment by benji6** [comment]
This is really cool, haven't taken a look at `Traversable` before, just trying to get my head around it and I'll look at adding it in. Thanks for the suggestion! 😊

**Comment by benji6** [comment]
Hey, I've raised this PR https://github.com/benji6/imlazy/pull/35 to add `traverse` to imlazy. Going to be honest - this is really pushing the limits of my understanding and have implemented it mostly by copying from Ramda 😅  If you want to take a look and have any feedback let me know otherwise I'll get it merged soon and release!

**Comment by masaeedu** [comment]
Hi @benji6. I haven't had a chance to look at it in too much detail, but I think there's an issue where you're using `module.exports.ap` whereas the `ap` that should be used is of the items the function is producing.

To give you a concrete example, suppose you have a list of urls like this: `const urls = ["https://google.com", "https://yahoo.com"]`. The type of this is `[String]`. Now suppose you have a function called `download :: String -> Promise Response`, where `Promise` is an applicative. The goal is to have `traverse(download)(urls)` produce a `Promise [String]`. The applicative that is to be used along the way is `Promise.ap`, not `Iterable.ap`.

Instead of just accepting `of`, I think you'll need to accept a whole module representing the applicative type, and get both `of` and `ap` from that, so that I can plug in promises, maybes, etc.

**Comment by benji6** [comment]
OK thanks that was super helpful and pointed out some of where I was going wrong! 😊 

I think I was a little confused because the [Ramda implementation](https://ramdajs.com/docs/#traverse) actually seems to deviate from the Static Land spec in that it takes `of` instead of the whole module. That makes sense because it is dispatching to Fantasy Land methods under the hood.

I have pushed a fixup commit (ffdd1711ac073e4ac4e5e54f16281f3c142ab2b0) that changes the implementation and adds a test with an applicative from [fun-task](https://github.com/rpominov/fun-task). I think this works now!

**Comment by masaeedu** [comment]
@benji6 Sweet, looks good. One thing you might want to try is deriving `transpose` from `traverse` and running all your transpose tests. It should be `const A = { of: imlazy.repeat, lift2: imlazy.zipWith }; const transpose = traverse(A)(x => x)`.

**Comment by benji6** [comment]
Yeah the derivations thing is super cool. Was reading this section https://github.com/rpominov/static-land/blob/master/docs/spec.md#can-be-derived-5 - my implementation of `traverse` depends on the provided module's `ap`, `of` and `map` functions and I'm not making use of `lift2` so I can't define `transpose` in that way. There is probably a way I can do it with `ap`, `of` and `map` though. Will have to have a think about it!

**Comment by masaeedu** [comment]
Ah, I see. Well `lift2` can be derived from `map` and `ap` using a [fairly simple formula](https://github.com/masaeedu/fp/blob/master/src/classes/apply.js#L6) and conversely `ap` [can be derived](https://github.com/masaeedu/fp/blob/master/src/classes/apply.js#L5) from `lift2`. Given that we have our "lift2" (i.e. `zipWith`), we want to produce the corresponding `ap`, so we just substitute:

```
const ap = ({ lift2 }) => lift2(x => x); // derivation of ap from lift2

// therefore
const zippyLift2 = zipWith
const zippyAp = zipWith(x => x)

// now let's plug it into your traverse
const transpose = traverse({ of: repeat, ap: zippyAp })(x => x)
```

**Comment by benji6** [comment]
Right, yes that's definitely a lot more elegant. There is a problem though in that my current implementation of `traverse` uses `reduceRight` so isn't lazy, but my current implementation of `transpose` is.

I can definitely feel the pull of trying to define all the functions in this lib as concisely as possible but have tended to not do that for the sake of performance, so I'm tempted for now to leave the `transpose` implementation as it is for now 🤷‍♂️ 

Btw thanks so much for all the info on Traversables - is super interesting and has really helped my understanding :)
